### ISSUE TITLE
Building devaluator fails with rpc error

### ISSUE THREAD

**Issue by EZ-Walk** [naetherm/SpellingBenchmark#1]
#  Running the build command to devaluator fails with: rpc error: code = Unknown desc = executor failed running
------
When I try to build and run the Benchmarker with the command supplied in the readme. However, I am stopped in this step of the build command: ` => ERROR [spellingbenchmark-master_evaluator 6/6] RUN dub build --build=debug --parallel devaluator`
On that line we get the following information:
> [spellingbenchmark-master_evaluator 6/6] RUN dub build --build=debug --parallel devaluator:
#12 0.457 Building package devaluator in /code/devaluator/
#12 3.202 Fetching snck 0.0.4 (getting selected version)...
#12 4.628 Fetching vibe-core 1.18.1 (getting selected version)...
#12 6.038 Fetching memutils 1.0.4 (getting selected version)...
#12 7.392 Fetching taggedalgebraic 0.11.22 (getting selected version)...
#12 8.617 Fetching botan-math 1.0.3 (getting selected version)...
#12 10.70 Fetching vibe-d 0.9.0 (getting selected version)...
#12 19.20 Fetching stdx-allocator 2.77.5 (getting selected version)...
#12 20.72 Fetching botan 1.12.19 (getting selected version)...
#12 26.95 Fetching diet-ng 1.7.7 (getting selected version)...
#12 28.21 Fetching openssl 1.1.6+1.0.1g (getting selected version)...
#12 31.28 Fetching darg 0.1.0 (getting selected version)...
#12 32.43 Fetching eventcore 0.9.17 (getting selected version)...
#12 33.85 Fetching mir-linux-kernel 1.0.1 (getting selected version)...
#12 35.23 Fetching libasync 0.8.6 (getting selected version)...
#12 36.94 Running pre-generate commands for vibe-d:tls...
#12 38.21 Performing "debug" build using /dlang/dmd-2.097.0-rc.1/linux/bin64/dmd for x86_64.
#12 38.21 darg 0.1.0: building configuration "library"...
#12 38.23 /root/.dub/packages/darg-0.1.0/darg/source/darg.d(146,5): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
#12 38.23 /root/.dub/packages/darg-0.1.0/darg/source/darg.d(159,5): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
#12 38.73 dutility ~master: building configuration "library"...
#12 38.87 snck 0.0.4: building configuration "library"...
#12 38.94 taggedalgebraic 0.11.22: building configuration "library"...
#12 39.01 eventcore 0.9.17: building configuration "epoll"...
#12 40.61 stdx-allocator 2.77.5: building configuration "library"...
#12 40.83 vibe-core 1.18.1: building configuration "epoll"...
#12 44.48 vibe-d:utils 0.9.0: building configuration "library"...
#12 45.15 vibe-d:data 0.9.0: building configuration "library"...
#12 46.65 mir-linux-kernel 1.0.1: building configuration "library"...
#12 46.72 vibe-d:crypto 0.9.0: building configuration "library"...
#12 47.07 diet-ng 1.7.7: building configuration "library"...
#12 47.92 vibe-d:stream 0.9.0: building configuration "library"...
#12 48.76 /root/.dub/packages/vibe-d-0.9.0/vibe-d/stream/vibe/stream/stdio.d(115,10): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 48.76 /root/.dub/packages/vibe-d-0.9.0/vibe-d/stream/vibe/stream/stdio.d(141,10): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 49.04 vibe-d:textfilter 0.9.0: building configuration "library"...
#12 49.87 vibe-d:inet 0.9.0: building configuration "library"...
#12 51.19 vibe-d:tls 0.9.0: building configuration "openssl"...
#12 53.82 vibe-d:http 0.9.0: building configuration "library"...
#12 57.37 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/proxy.d(113,11): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 57.39 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/proxy.d(161,12): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/range/primitives.d(175,38): Deprecation: `alias byKeyValue this` is deprecated - Iterate over .byKeyValue instead.
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2867,14):        instantiated from here: `isInputRange!(DictionaryList!(string, true, 16LU, false))`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2548,5):        instantiated from here: `enforceValidFormatSpec!(DictionaryList!(string, true, 16LU, false), char)`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/write.d(1239,20):        instantiated from here: `formatValueImpl!(Appender!string, DictionaryList!(string, true, 16LU, false), char)`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2927,24):        ... (1 instantiations, -v to show) ...
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2905,17):        instantiated from here: `toString!(Appender!string)`
#12 58.09 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/server.d(949,3):        instantiated from here: `Nullable!(DictionaryList!(string, true, 16LU, false))`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/range/primitives.d(177,27): Deprecation: `alias byKeyValue this` is deprecated - Iterate over .byKeyValue instead.
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2867,14):        instantiated from here: `isInputRange!(DictionaryList!(string, true, 16LU, false))`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2548,5):        instantiated from here: `enforceValidFormatSpec!(DictionaryList!(string, true, 16LU, false), char)`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/write.d(1239,20):        instantiated from here: `formatValueImpl!(Appender!string, DictionaryList!(string, true, 16LU, false), char)`
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2927,24):        ... (1 instantiations, -v to show) ...
#12 58.09 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2905,17):        instantiated from here: `toString!(Appender!string)`
#12 58.09 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/server.d(949,3):        instantiated from here: `Nullable!(DictionaryList!(string, true, 16LU, false))`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/range/primitives.d(175,38): Deprecation: `alias byKeyValue this` is deprecated - Iterate over .byKeyValue instead.
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2867,14):        instantiated from here: `isInputRange!(const(DictionaryList!(string, true, 16LU, false)))`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2548,5):        instantiated from here: `enforceValidFormatSpec!(const(DictionaryList!(string, true, 16LU, false)), char)`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/write.d(1239,20):        instantiated from here: `formatValueImpl!(Appender!string, const(DictionaryList!(string, true, 16LU, false)), char)`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2938,24):        ... (1 instantiations, -v to show) ...
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2915,17):        instantiated from here: `toString!(Appender!string)`
#12 58.10 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/server.d(949,3):        instantiated from here: `Nullable!(DictionaryList!(string, true, 16LU, false))`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/range/primitives.d(177,27): Deprecation: `alias byKeyValue this` is deprecated - Iterate over .byKeyValue instead.
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2867,14):        instantiated from here: `isInputRange!(const(DictionaryList!(string, true, 16LU, false)))`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/internal/write.d(2548,5):        instantiated from here: `enforceValidFormatSpec!(const(DictionaryList!(string, true, 16LU, false)), char)`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/format/write.d(1239,20):        instantiated from here: `formatValueImpl!(Appender!string, const(DictionaryList!(string, true, 16LU, false)), char)`
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2938,24):        ... (1 instantiations, -v to show) ...
#12 58.10 /dlang/dmd-2.097.0-rc.1/linux/bin64/../../src/phobos/std/typecons.d(2915,17):        instantiated from here: `toString!(Appender!string)`
#12 58.10 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/server.d(949,3):        instantiated from here: `Nullable!(DictionaryList!(string, true, 16LU, false))`
#12 58.26 /root/.dub/packages/vibe-d-0.9.0/vibe-d/http/vibe/http/websockets.d(556,22): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 62.54 vibe-d:mail 0.9.0: building configuration "library"...
#12 63.94 vibe-d:mongodb 0.9.0: building configuration "library"...
#12 66.34 vibe-d:redis 0.9.0: building configuration "library"...
#12 67.47 /root/.dub/packages/vibe-d-0.9.0/vibe-d/redis/vibe/db/redis/redis.d(1179,29): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 67.48 /root/.dub/packages/vibe-d-0.9.0/vibe-d/redis/vibe/db/redis/redis.d(1275,24): Deprecation: template `vibe.core.core.runTask(ARGS...)(void delegate(ARGS) @safe task, auto ref ARGS args)` is deprecated - The `task` argument should be nothrow
#12 68.22 vibe-d:web 0.9.0: building configuration "library"...
#12 69.82 vibe-d 0.9.0: building configuration "vibe-core"...
#12 70.87 devaluator ~master: building configuration "application"...
#12 71.21 /root/.dub/packages/darg-0.1.0/darg/source/darg.d(146,5): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
#12 71.21 /root/.dub/packages/darg-0.1.0/darg/source/darg.d(159,5): Deprecation: Usage of the `body` keyword is deprecated. Use `do` instead.
#12 81.45 Killed
#12 81.49 /dlang/dmd-2.097.0-rc.1/linux/bin64/dmd failed with exit code 137.`
------
And then finally the exit status
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c dub build --build=debug --parallel devaluator]: exit code: 2

**Comment by naetherm** [comment]
Thx for the report, I will take a look into that as soon as possible.

**Comment by naetherm** [comment]
Works fine for me. 
Do you have enough RAM?

If you are using Docker on Windows or Mac you can easily increase it by going to Preferences -> Advanced.

**Comment by EZ-Walk** [comment]
No I did not, increasing the RAM allocation to 4GB solved that issue.
